# Generated by Django 5.0 on 2023-12-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
